import checkJs from "./modules/checkJs";
import download from "./modules/download";
import whatSlider from "./modules/whatSlider";
import menu from "./modules/menu";
import table from "./modules/resizeTable";
import modal from "./modules/modal";
import scroll from "./modules/scroll";
import headerFixed from "./modules/headerFixed";
import parallax from "./modules/parallax";
import mask from "./modules/mask";

checkJs();
download();
whatSlider();
menu();
table();
modal();
scroll();
headerFixed();
parallax();
mask();
